# Generated by Django 5.0.1 on 2024-01-13 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_variantimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='thumbnail',
        ),
    ]
