# Generated by Django 5.0.1 on 2024-01-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_variantimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantimage',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
