# Generated by Django 5.0.1 on 2024-01-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_variantimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='saveForLater',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(blank=True, default='designing', max_length=100),
        ),
        migrations.AlterField(
            model_name='variant',
            name='default',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='variantimage',
            name='alt',
            field=models.CharField(blank=True, default='Image for Variant', max_length=100),
        ),
    ]
