# Generated by Django 5.0.1 on 2024-01-20 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_slug_alter_cartitem_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='default',
        ),
    ]
