# Generated by Django 5.0.1 on 2024-01-26 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_product_options_product_removed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
