# Generated by Django 5.0.1 on 2024-02-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_remove_orderproductitem_user_orderitem_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail_alt',
            field=models.CharField(blank=True, default='Image for Product', max_length=250),
        ),
        migrations.AlterField(
            model_name='variantimage',
            name='alt',
            field=models.CharField(blank=True, default='Image for Variant', max_length=250),
        ),
    ]
