# Generated by Django 5.0.1 on 2024-02-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_alter_product_thumbnail_alter_variantimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='time_payed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(upload_to='products_thumbnails/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='variantimage',
            name='image',
            field=models.ImageField(upload_to='variants_images/%Y/%m/%d'),
        ),
    ]
