# Generated by Django 5.0.1 on 2024-02-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_review_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
