# Generated by Django 5.0.1 on 2024-01-16 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_emailverification_time_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
