# Generated by Django 5.0.1 on 2024-01-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_emailverification_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
