# Generated by Django 5.0.1 on 2024-01-16 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_emailverification_blocked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverification',
            name='requests',
        ),
    ]
