# Generated by Django 5.0.1 on 2024-02-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='/default_avatars/default.svg', upload_to='users_avatars'),
            preserve_default=False,
        ),
    ]
